In [1]:
# import libraries

import pandas as pd
from spacy import displacy
import spacy

In [2]:
# Require text example - lord of rings: name and race

url = "https://raw.githubusercontent.com/juandes/lotr-names-classification/master/characters_data.csv"
df = pd.read_csv(url)
df

           name race
0    Aragorn II  Man
1         Arwen  Elf
2        Elrond  Elf
3     Celebrían  Elf
4       Elrohir  Elf
..          ...  ...
822      Brodda  Man
823      Annael  Elf
824      Gelmir  Elf
825     Arminas  Elf
826      Gildor  Man

[827 rows x 2 columns]